import type { Category, Transaction } from "./types";

export const categories: Category[] = [
  {
    key: "eating-out",
    label: "Eating out",
    emoji: "🍔",
    colorBg: "var(--kw-orange-soft)",
    colorFg: "var(--kw-orange)",
  },
  {
    key: "utilities",
    label: "Utilities",
    emoji: "☎️",
    colorBg: "var(--kw-purple-soft)",
    colorFg: "var(--kw-purple)",
  },
  {
    key: "transport",
    label: "Transport",
    emoji: "🚌",
    colorBg: "var(--kw-teal-soft)",
    colorFg: "var(--kw-teal)",
  },
  {
    key: "shopping",
    label: "Shopping",
    emoji: "🛍️",
    colorBg: "var(--kw-orange-soft)",
    colorFg: "var(--kw-orange)",
  },
  {
    key: "salary",
    label: "Salary",
    emoji: "💼",
    colorBg: "var(--kw-success-soft)",
    colorFg: "var(--kw-success)",
  },
  {
    key: "transfer",
    label: "Transfer",
    emoji: "🔁",
    colorBg: "var(--kw-teal-soft)",
    colorFg: "var(--kw-teal)",
  },
  {
    key: "uncategorized",
    label: "Uncategorized",
    emoji: "❔",
    colorBg: "#f1f2f9",
    colorFg: "var(--kw-muted)",
  },
];

export const utilitySubcategories = ["Lawma", "Power", "Water", "Rent"];

export const transactions: Transaction[] = [
  {
    id: "t1",
    name: "Transfer from Customer",
    initial: "C",
    avatarBg: "#eef0fb",
    avatarFg: "#372ee0",
    amount: 122000,
    direction: "credit",
    date: "2026-07-22T10:03:00",
    group: "Today",
    category: "salary",
    description: "Daily sales deposit",
    remark: "Mwapanga deposit ya MWK 122,000",
    tag: "business",
    rawSms: "Mwapanga deposit ya MWK 122,000 at agent 123456. Airtel Money.",
    status: "processed",
    processedAt: "2026-07-22T10:05:00",
  },
  {
    id: "t2",
    name: "Kwacha Supermarket",
    initial: "K",
    avatarBg: "#eef0fb",
    avatarFg: "#372ee0",
    amount: 18500,
    direction: "debit",
    date: "2026-07-22T11:30:00",
    group: "Today",
    category: "shopping",
    description: "Groceries for shop restock",
    tag: "business",
    status: "processed",
    processedAt: "2026-07-22T11:35:00",
  },
  {
    id: "t3",
    name: "Family Groceries",
    initial: "F",
    avatarBg: "#fef3c7",
    avatarFg: "#92400e",
    amount: 8500,
    direction: "debit",
    date: "2026-07-22T12:15:00",
    group: "Today",
    category: "shopping",
    description: "Home groceries",
    tag: "personal",
    status: "processed",
    processedAt: "2026-07-22T12:20:00",
  },
  {
    id: "t4",
    name: "Transfer to Phillip",
    initial: "P",
    avatarBg: "#eef0fb",
    avatarFg: "#372ee0",
    amount: 50000,
    direction: "credit",
    date: "2026-07-21T09:00:00",
    group: "Yesterday",
    category: "transfer",
    description: "Payment for coffee beans",
    remark: "Transfer to Phillip",
    tag: "business",
    status: "processed",
    processedAt: "2026-07-21T09:05:00",
  },
  {
    id: "t5",
    name: "School Fees",
    initial: "S",
    avatarBg: "#fef3c7",
    avatarFg: "#92400e",
    amount: 25000,
    direction: "debit",
    date: "2026-07-21T08:45:00",
    group: "Yesterday",
    category: "uncategorized",
    description: "Children school fees",
    tag: "personal",
    status: "processed",
    processedAt: "2026-07-21T08:50:00",
  },
  {
    id: "t6",
    name: "Merchant Payment",
    initial: "M",
    avatarBg: "#eef0fb",
    avatarFg: "#372ee0",
    amount: 42000,
    direction: "debit",
    date: "2026-07-21T14:20:00",
    group: "Yesterday",
    category: "transfer",
    description: "Supplier payment",
    tag: "business",
    status: "processed",
    processedAt: "2026-07-21T14:25:00",
  },
  {
    id: "t7",
    name: "Airtime Purchase",
    initial: "A",
    avatarBg: "#eef0fb",
    avatarFg: "#372ee0",
    amount: 5000,
    direction: "debit",
    date: "2026-07-20T16:30:00",
    group: "Yesterday",
    category: "utilities",
    description: "Airtime for business calls",
    tag: "business",
    status: "processed",
    processedAt: "2026-07-20T16:35:00",
  },
  {
    id: "t8",
    name: "Salary Credit",
    initial: "N",
    avatarBg: "#eef0fb",
    avatarFg: "#372ee0",
    amount: 350000,
    direction: "credit",
    date: "2026-07-20T00:00:00",
    group: "Yesterday",
    category: "salary",
    description: "Monthly salary from employer",
    tag: "personal",
    status: "processed",
    processedAt: "2026-07-20T00:05:00",
  },
  {
    id: "t9",
    name: "Deposit from customer",
    initial: "D",
    avatarBg: "#eef0fb",
    avatarFg: "#372ee0",
    amount: 45000,
    direction: "credit",
    date: "2026-07-23T08:15:00",
    group: "Today",
    category: "uncategorized",
    description: "Morning deposit from shop sales",
    tag: "business",
    rawSms: "Mwapanga deposit ya MWK 45,000 at agent 445566. Airtel Money.",
    status: "unprocessed",
  },
  {
    id: "t10",
    name: "POS Purchase",
    initial: "P",
    avatarBg: "#fef3c7",
    avatarFg: "#92400e",
    amount: 12000,
    direction: "debit",
    date: "2026-07-23T09:45:00",
    group: "Today",
    category: "uncategorized",
    description: "Lunch and transport",
    tag: "personal",
    rawSms: "POS Purchase-Club Teknayo--Lunch T La Lang-",
    status: "unprocessed",
  },
  {
    id: "t11",
    name: "Transfer received",
    initial: "T",
    avatarBg: "#eef0fb",
    avatarFg: "#372ee0",
    amount: 80000,
    direction: "credit",
    date: "2026-07-23T11:00:00",
    group: "Today",
    category: "uncategorized",
    description: "Payment from client",
    tag: "business",
    rawSms: "You have received MK 80,000 from John Banda. Ref: TXN99887766. NBM.",
    status: "unprocessed",
  },
  {
    id: "t12",
    name: "Merchant Payment",
    initial: "M",
    avatarBg: "#eef0fb",
    avatarFg: "#372ee0",
    amount: 15000,
    direction: "debit",
    date: "2026-07-23T13:20:00",
    group: "Today",
    category: "uncategorized",
    description: "Fuel for delivery",
    tag: "business",
    rawSms: "Merchant Payment-Lilongwe Boma Motors--Fuel T La Lang-",
    status: "unprocessed",
  },
  {
    id: "t13",
    name: "Cash Out",
    initial: "C",
    avatarBg: "#fef3c7",
    avatarFg: "#92400e",
    amount: 20000,
    direction: "debit",
    date: "2026-07-23T15:45:00",
    group: "Today",
    category: "uncategorized",
    description: "Airtime for home",
    tag: "personal",
    rawSms: "Cash Out-Kunda Agencies--Airtime T La Lang-",
    status: "unprocessed",
  },
  {
    id: "t14",
    name: "POS Purchase",
    initial: "P",
    avatarBg: "#eef0fb",
    avatarFg: "#372ee0",
    amount: 8500,
    direction: "debit",
    date: "2026-07-23T17:10:00",
    group: "Today",
    category: "uncategorized",
    description: "Office supplies",
    tag: "business",
    rawSms: "POS Purchase-Kuda Stationaries--Paper T La Lang-",
    status: "unprocessed",
  },
  {
    id: "t15",
    name: "Deposit",
    initial: "D",
    avatarBg: "#eef0fb",
    avatarFg: "#372ee0",
    amount: 60000,
    direction: "credit",
    date: "2026-07-23T18:30:00",
    group: "Today",
    category: "uncategorized",
    description: "Evening sales deposit",
    tag: "business",
    rawSms: "Mwapanga deposit ya MWK 60,000 at agent 778899. Airtel Money.",
    status: "unprocessed",
  },
];

export const categorizeQueue = [
  {
    id: "c1",
    name: "Kwacha Supermarket",
    amount: 18500,
    date: "2026-07-22 11:30",
    remark: "POS Purchase-Kwacha Supermarket--Groceries-",
    suggestion: categories.find((c) => c.key === "shopping")!,
    subcategories: ["Groceries", "Clothing", "Electronics", "Household"],
  },
  {
    id: "c2",
    name: "Airtime Purchase",
    amount: 5000,
    date: "2026-07-22 16:30",
    remark: "Airtime & Bundle Purchase-Ref 88213--Self Top Up-",
    suggestion: categories.find((c) => c.key === "utilities")!,
    subcategories: ["Airtime", "Internet", "Power", "Water"],
  },
  {
    id: "c3",
    name: "Merchant Payment",
    amount: 42000,
    date: "2026-07-21 14:20",
    remark: "Merchant Payment-Lilongwe Boma Motors--Fuel T La Lang-",
    suggestion: categories.find((c) => c.key === "transport")!,
    subcategories: ["Fuel", "Minibus", "Taxi", "Repairs"],
  },
  {
    id: "c4",
    name: "Restaurant Payment",
    amount: 12500,
    date: "2026-07-21 19:45",
    remark: "POS Purchase-Habib Yogurt Shop--Snacks T La Lang-",
    suggestion: categories.find((c) => c.key === "eating-out")!,
    subcategories: ["Restaurant", "Snacks", "Coffee", "Delivery"],
  },
  {
    id: "c5",
    name: "Salary Credit",
    amount: 350000,
    date: "2026-07-20 00:00",
    remark: "Salary Credit-Code Collective Ltd--Monthly Pay-",
    suggestion: categories.find((c) => c.key === "salary")!,
    subcategories: ["Salary", "Bonus", "Freelance", "Other income"],
  },
];

export function formatMWK(amount: number) {
  return `K${amount.toLocaleString("en-US")}`;
}
